project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
api_token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

files:
  - source: /lib/l10n/app_en.arb
    translation: /lib/l10n/app_%locale%.arb
    languages_mapping:
      locale:
        af: af
        ar: ar
        de: de
        es: es
        fr: fr
        it: it
        ja: ja
        ko: ko
        pt-BR: pt_BR
        ru: ru
        zh-CN: zh_CN
        zh-TW: zh_TW

structure: /lib/l10n/app_%locale%.arb